name: soa-ilec
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - alsa-lib=1.2.14
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - binutils_impl_linux-64=2.44
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.11
  - cuda-version=12.9
  - curl=8.14.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gflags=2.2.2
  - gfortran_impl_linux-64=15.2.0
  - glog=0.7.1
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.2
  - libclang13=21.1.2
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm21=21.1.2
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.0
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - libsanitizer=15.2.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libuuid=2.41.2
  - libvulkan-loader=1.4.313.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.0.5
  - libxkbcommon=1.11.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mistune=3.1.4
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.27.7.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8.1
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-duckdb=1.4.1
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.11
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - r-arrow=21.0.0
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-broom=1.0.10
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-dbplyr=2.5.1
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.2
  - r-duckdb=1.4.0
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.1
  - r-foreach=1.5.2
  - r-fs=1.6.6
  - r-gargle=1.6.0
  - r-generics=0.1.4
  - r-ggplot2=4.0.0
  - r-glmnet=4.1_10
  - r-glue=1.8.0
  - r-googledrive=2.1.2
  - r-googlesheets4=1.1.2
  - r-gtable=0.3.6
  - r-haven=2.5.5
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lattice=0.22_7
  - r-lifecycle=1.0.4
  - r-lubridate=1.9.4
  - r-magrittr=2.0.4
  - r-matrix=1.7_4
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-openssl=2.3.4
  - r-pillar=1.11.1
  - r-pkgconfig=2.0.3
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-progress=1.2.3
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-r6=2.6.1
  - r-ragg=1.5.0
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=15.0.2_2
  - r-rcppeigen=0.3.4.0.2
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-rlang=1.1.6
  - r-rmarkdown=2.30
  - r-rpart=4.1.24
  - r-rpart.plot=3.1.3
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.5
  - r-s7=0.2.0
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-shape=1.4.6.1
  - r-splines2=0.5.4
  - r-stringi=1.8.7
  - r-stringr=1.5.2
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.3.1
  - r-textshaping=1.0.3
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.57
  - r-tzdb=0.5.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.6
  - r-withr=3.0.2
  - r-xfun=0.53
  - r-xgboost=3.0.5
  - r-xml2=1.4.0
  - r-yaml=2.3.10
  - re2=2025.08.12
  - readline=8.2
  - referencing=0.36.2
  - regex=2025.9.18
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - rpy2=3.6.4
  - s2n=1.5.26
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sysroot_linux-64=2.34
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tiktoken=0.12.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - authlib==1.6.5
      - backoff==2.2.1
      - click==8.3.0
      - colorama==0.4.6
      - cryptography==46.0.2
      - cyclopts==3.24.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - duckdb-engine==0.17.0
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - fastmcp==2.12.4
      - frozenlist==1.8.0
      - greenlet==3.2.4
      - griffe==1.14.0
      - httpx-sse==0.4.2
      - ipython-genutils==0.2.0
      - isodate==0.7.2
      - jiter==0.11.0
      - jsonpatch==1.33
      - jsonschema-path==0.3.4
      - jsonschema-pydantic==0.6
      - jupysql==0.11.1
      - jupysql-plugin==0.4.5
      - langchain==0.3.27
      - langchain-core==0.3.78
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.33
      - lazy-object-proxy==1.12.0
      - markdown-it-py==4.0.0
      - mcp==1.16.0
      - mcp-use==1.3.11
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - multidict==6.7.0
      - openai==1.109.1
      - openai-agents==0.3.3
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - openpyxl==3.1.5
      - orjson==3.11.3
      - parse==1.20.2
      - pathable==0.4.4
      - ploomber-core==0.2.27
      - posthog==6.7.6
      - prettytable==3.16.0
      - propcache==0.4.1
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydantic-settings==2.11.0
      - pyperclip==1.11.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rich-rst==1.3.1
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - scarf-sdk==0.1.3
      - sqlalchemy==2.0.43
      - sqlglot==27.26.0
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - tenacity==9.1.2
      - tqdm==4.67.1
      - types-requests==2.32.4.20250913
      - typing-inspection==0.4.2
      - uvicorn==0.37.0
      - websockets==15.0.1
      - werkzeug==3.1.1
      - yarl==1.22.0
